---
- name: Apply common system updates
  hosts: web
  become: yes
  roles:
    - common

- name: Install and Configure nginx
  hosts: web
  become: yes
  roles:
    - nginx

- name: Deploy Epicbook application
  hosts: web
  become: yes
  roles:
    - epicbook

- name: Verify Epicbook is accessible
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check website is reachable
      uri:
        url: "http://{{ groups['web'][0] }}"
        status_code: 200
      register: site_check
      retries: 10
      delay: 5
      until: site_check.status == 200

    - name: Confirm success
      debug:
        msg: "EpicBook is live!"
